language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO_VERSION=2.0
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.7
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install coverage
  - pip install coveralls
script:
  - cd example && coverage run --source=django_grapesjs --omit=*/migrations/*,*/tests/* manage.py test django_grapesjs
after_success:
  - cd example && coverage report
  - cd example && coveralls
matrix:
  exclude:
  - python: "3.3"
    env: DJANGO_VERSION=2.0
  - python: "3.3"
    env: DJANGO_VERSION=1.11
  - python: "3.3"
    env: DJANGO_VERSION=1.10
  - python: "3.3"
    env: DJANGO_VERSION=1.9
  - python: "3.5"
    env: DJANGO_VERSION=1.7
  - python: "3.6"
    env: DJANGO_VERSION=1.7